spring:
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  servlet:
    multipart:
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      access-key: ENC(vddcKGLGK7uW5FuMCppk/9KrEpqOLD1bv9MwgGcriQE=)
      secret-key: ENC(MmqBJCNvh4dUz7oxFIxYhd+i4LUjfXs0KZwOz9+Vfco2WkXU4/boAkG9iwoP1xgjTkhRM3G2fC0=)
    s3:
      bucket: danggnmarket-challenge-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
server:
  tomcat:
    use-relative-redirects: true
---
spring:
  config:
    activate:
      on-profile: prod1
  datasource:
    url: ENC(rff/3AqNQg7Nl3j3lAgwjlt+P2BSATog3b5KoWmLTArRqhxVB6Us1JPHMbxqAhzCBrxQGflQBAKEyzbnDQ5cckmqCBg8hcltIU/f2KhPJR4qw6PNlwgI+O2lzHOsqdVnRwv16h+fTAl+/WGTEgyKJ2fgs+frWmH0V3mF2fVtRuMFThqm9qEn7v4cvtNIa+Ej)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(EtYPV83KhfOyXb7SdMEGbw==)
    password: ENC(Nhc6LlFYfE2ye+JfZHAV20+EC3WIp9Go)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: false
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod2
  datasource:
    url: ENC(rff/3AqNQg7Nl3j3lAgwjlt+P2BSATog3b5KoWmLTArRqhxVB6Us1JPHMbxqAhzCBrxQGflQBAKEyzbnDQ5cckmqCBg8hcltIU/f2KhPJR4qw6PNlwgI+O2lzHOsqdVnRwv16h+fTAl+/WGTEgyKJ2fgs+frWmH0V3mF2fVtRuMFThqm9qEn7v4cvtNIa+Ej)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(EtYPV83KhfOyXb7SdMEGbw==)
    password: ENC(Nhc6LlFYfE2ye+JfZHAV20+EC3WIp9Go)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: false
server:
  port: 8082
