spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  servlet:
    multipart:
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      access-key: ENC(vddcKGLGK7uW5FuMCppk/9KrEpqOLD1bv9MwgGcriQE=)
      secret-key: ENC(MmqBJCNvh4dUz7oxFIxYhd+i4LUjfXs0KZwOz9+Vfco2WkXU4/boAkG9iwoP1xgjTkhRM3G2fC0=)
    s3:
      bucket: danggnmarket-challenge-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
